matrix:
  include:
    - language: python
      python: 3.7
      script:
        - pip install -r flake8
        - flake8 .
    - language: node_js
      node_js:
        - "10"
      script:
        - npm install eslint
        - eslint .
